### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fabiocaccamo** [leoboiko/uniscripts#1]
Hello, 
I'm trying to install this package via pip `pip install uniscripts`, but it raises the following error:
```python
  ERROR: Command errored out with exit status 1:
   command: /Users/fabiocaccamo/Documents/libs/python/python-fontbro/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xx/75nbxc0x1nv4h1qkkz4rmkf40000gn/T/pip-install-kfnrr0rs/uniscripts_12162aec5e4640f8848483461e32c612/setup.py'"'"'; __file__='"'"'/private/var/folders/xx/75nbxc0x1nv4h1qkkz4rmkf40000gn/T/pip-install-kfnrr0rs/uniscripts_12162aec5e4640f8848483461e32c612/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/xx/75nbxc0x1nv4h1qkkz4rmkf40000gn/T/pip-pip-egg-info-32k7q1qu
       cwd: /private/var/folders/xx/75nbxc0x1nv4h1qkkz4rmkf40000gn/T/pip-install-kfnrr0rs/uniscripts_12162aec5e4640f8848483461e32c612/
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/private/var/folders/xx/75nbxc0x1nv4h1qkkz4rmkf40000gn/T/pip-install-kfnrr0rs/uniscripts_12162aec5e4640f8848483461e32c612/setup.py", line 14, in <module>
      import pypandoc
  ModuleNotFoundError: No module named 'pypandoc'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/xx/75nbxc0x1nv4h1qkkz4rmkf40000gn/T/pip-install-kfnrr0rs/uniscripts_12162aec5e4640f8848483461e32c612/setup.py", line 17, in <module>
      with open(path.join(here, 'README.md')) as f:
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 905, in open
      file = builtins.open(filename, mode, buffering)
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/xx/75nbxc0x1nv4h1qkkz4rmkf40000gn/T/pip-install-kfnrr0rs/uniscripts_12162aec5e4640f8848483461e32c612/README.md'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/83/af/61a5d4ca443e0bac1ffc11481abdf486f5d1ddba4f665e1e5ab0a091debc/uniscripts-1.0.5.tar.gz#sha256=ac2e3fab0db570466958eb759d4143b67cae12766484ea98aef8911b31d2e309 (from https://pypi.org/simple/uniscripts/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by melissaboiko** [comment]
Hi! This project is defunct and I have no idea whether it still works.  But you can solve the error above by runing `pip install pypandoc` before it.
